'''MAKE A PROGRAM USING LOOPS IN WHICH YOU DETERMINE A NUMBER AND THE USER WILL HAVE TO ENTER THAT NUMBER TO WIN
 1. THE CHANCES MUST BE LIMITED
 2. AFTER THE CHANCES ARE OVER GAME SHOULD BE OVER
 '''